<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_form_alter().
 */
function club_event_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'webform_submission_free_event_delete_form') {
    // Shorten the default "delete confirmation" message to make if "friendlier" for users.
    // Default: "Warning message: Are you sure you want to delete the [event name]: Submission #[xxx]? This action cannot be undone.
    //  This action will ... Remove records from the database, Delete any uploaded files, Cancel all pending actions. 

    // Get event title and remove the part after the colon which is "Submission #XXX".
    $title = $form['#title']->getArguments('%label');
    $event_name = explode(':',reset($title));
    $form['#title'] = 'Cancel registration for ' . $event_name[0];

    $form['warning']['#message_type'] = NULL;  // Remove type to remove the "Warning message" header.
    $form['warning']['#message_message'] = 'Are you sure you want to delete registration for <strong>' . $event_name[0] . '</strong>?'; 
    $form['description'] = NULL;
  }
}

/**
 * Implements hook_form_FORM_alter().
 */
function club_event_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  if ( in_array($form_id, ['node_webform_form','node_webform_edit_form','node_webform_quick_node_clone_form',
                           'node_event_form','node_event_edit_form','node_event_quick_node_clone_form', ])) {
    // Hide Summary field if Promote to front page is unchecked.
    $form['field_summary']['#states'] = [
      'invisible' => [
       ':input[name^="promote"]' => ['unchecked' => TRUE],
      ],
    ];

    // Show text area or paragraphs components, depending on 'type of page'.
    $form['field_text']['#states'] = [
      'visible' => [
        ':input[name^="field_type_of_page"]' => ['value' => 1],
      ],
    ];
    $form['field_components']['#states'] = [
      'visible' => [
        ':input[name^="field_type_of_page"]' => ['value' => 2],
      ],
    ];

    // Change '- None -' to '- All -' on Page visibility dropdown
    $form['field_page_access']['widget']['#options']['_none'] = '- All -';

    $form['field_contact_person']['#states'] = [
      'visible' => [
        ':input[name^="field_contact_form"]' => ['value' => 'personal'],
      ],
    ];

    // Form fields in Events but not webforms.
    if ( in_array($form_id, ['node_event_form','node_event_edit_form','node_event_quick_node_clone_form', ])) {
      
      // Show Location and Date if event page.
      $form['field_location']['#states'] = [
        'visible' => [
          ':input[name^="field_event_page"]' => ['value' => 1],
        ],
      ];

      // Show free registration form, paid registration form, or registration link - depending on type of event.
      $form['field_registration_free_form']['#states'] = [
        'visible' => [
          ':input[name="field_registration"]' => ['value' => 1],
        ],
      ];
      $form['field_registration_form']['#states'] = [
        'visible' => [
          ':input[name="field_registration"]' => ['value' => 2],
        ],
      ];
      $form['field_registration_link']['#states'] = [
        'visible' => [
          ':input[name="field_registration"]' => ['value' => 3],
        ],
      ];

      // Show "Results are visible to" if free event or paid webform.
      $form['field_results_access']['#states'] = [
        'visible' => [
          [':input[name="field_registration"]' => ['value' => '1']],
          'or',
          [':input[name="field_registration"]' => ['value' => '2']],
        ],        
      ];

      // Remove instructions "begin typing" ...
      $form['field_registration_link']['widget'][0]['uri']['#description'] = NULL;
    }
  }
}

/**
 * Implements hook_node_presave().
 *
 */
function club_event_node_presave(EntityInterface $node) {

  // Clear registration fields depending on registration type (field_registration)
  // 0 = No registration, 1 = Free, 2 = Paid webform, 3 = Paid link
  if ($node->bundle() == 'event') {
    $regType = $node->get('field_registration')->value;

    if ($regType <> NULL) {
      if($regType <> 1 and $node->hasField('field_registration_free_form')) {
          $node->field_registration_free_form->target_id = NULL;
      }
      if($regType <> 2 and $node->hasField('field_registration_form')) {
        $i = 0;
        while (isset($node->get('field_registration_form')[$i]->target_id)) {
          $node->get('field_registration_form')[$i]->target_id = NULL;
          $i++;
        }
      }
      if($regType <> 3 and $node->hasField('field_registration_link')) {
        $i = 0;
        if (isset($node->get('field_registration_link')[$i])) {
          $node->get('field_registration_link')[$i]->uri = NULL;
          $i++;
        }
      }
      if($regType ==0) {
        unset($node->field_registration_close_date);
      } 
    }
  }
}

/**
 * Hide RESULTS tab on Events page except for users who are:
 *  Administrator or Site Admin role, node author, or listed in field_results_access.
 */
function club_event_menu_local_tasks_alter(&$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability) {
  
  if(\Drupal::currentUser()->isAuthenticated() and $route_name == 'entity.node.canonical'){

     // Hide "Test" tab and rename results tab.
     unset($data['tabs'][0]['entity.node.webform.test_form']);
     $data['tabs'][0]['entity.node.webform.results']['#link']['title'] = t('Registrations');

    // Initialize results access to NO.
    $access = 0;

    $node = \Drupal::routeMatch()->getParameter('node');
    $author = $node->getOwner()->id();

    $currentUser = \Drupal::currentUser()->id();
    $roles = \Drupal::currentUser()->getRoles();

    // If role is Admin or Site Admin or user is author -> grant access
    if (in_array('administrator',$roles) or in_array('site_admin',$roles) or $author == $currentUser) {
      $access = 1;
    } else {
      // For each user specified in "Results visible to", grant access
      if ($node->field_results_access) {
        foreach ($node->field_results_access->getValue() as $i) {
          if ($i['target_id'] == $currentUser) {
            $access = 1;
            break;
          }
        } 
      }
    }

    if ($access == 0) {
      unset($data['tabs'][0]['entity.node.webform.results']);
    }
  }
}
