<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_presave().
 *
 */
function club_schedule_node_presave(EntityInterface $node) {
  $bundle = $node->bundle();

  // If Ride, fill schedule date (entity reference field)
  if($bundle == 'ride') {

		if ($node->field_date->value) {
			$date_formatter = \Drupal::service('date.formatter');
			$date = $date_formatter->format($node->get('field_date')->date->getTimestamp(), 'custom', 'Y-m-d');

			$id = \Drupal::entityQuery("club_schedule")
				->accessCheck(FALSE)
				->condition('field_schedule_date', $date, '=')
				->execute();
			$id = reset($id);

			if ($id) {
				$node->field_schedule_date->target_id = $id;
			}
	  }
  }
}
