<?php

/**
 * Implements hook_theme().
 */
function club_paragraph_theme($existing, $type, $theme, $path) {
  // Adding 'uri' to variables so its available in template.
  return [
    'fontawesomeicons' => [
      'variables' => [
        'icons' => NULL,
        'layers' => FALSE,
      ],
    ],
    'fontawesomeicon' => [
      'variables' => [
        'tag' => 'i',
        'iconset' => '',
        'name' => NULL,
        'style' => NULL,
        'settings' => NULL,
        'transforms' => NULL,
        'mask' => NULL,
        'css' => NULL,
        'uri' => NULL,
      ],
    ],
  ];
}
