<?php

use Drupal\club\ImageCategory;
use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_link_alter().
 */
function club_page_link_alter(&$variables) {
  // Replace "Home" menu item with icon.
  if ($variables['text'] == 'Home' & $variables['text'] <> '0') {
    $variables['options']['attributes']['class'] = 'w3-button';
    $variables['text'] = t('<i class="fa fa-home fa-lg" aria-hidden="true"></i>');
  }
}

/**
 * Implements hook_form_FORM_alter().
 */
function club_page_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  if ( in_array($form_id, ['node_page_form','node_page_edit_form','node_page_quick_node_clone_form'] )) {
    // Show text area or paragraphs components, depending on 'type of page'.
    $form['field_text']['#states'] = [
      'visible' => [
        ':input[name^="field_type_of_page"]' => ['value' => 1],
      ],
    ];
    $form['field_components']['#states'] = [
      'visible' => [
        ':input[name^="field_type_of_page"]' => ['value' => 2],
      ],
    ];

    // Change '- None -' to '- All -' on Page visibility dropdown
    $form['field_page_access']['widget']['#options']['_none'] = '- All -';

    // Hide Sticky-on-top and Summary field if Promote to front page is unchecked.
    $form['sticky']['#states'] = [
      'invisible' => [
         ':input[name^="promote"]' => ['unchecked' => TRUE],
       ],
     ];

    $form['field_summary']['#states'] = [
     'invisible' => [
        ':input[name^="promote"]' => ['unchecked' => TRUE],
      ],
    ];
  }
}

/**
 * Implements hook_node_presave().
 *
 */
function club_page_node_presave(EntityInterface $node) {

  // Parse media UUIDs from text and summary fields (Basic page, Announcement, Event)
  $fields = ['field_summary','field_text'];
  $uuids = [];

  foreach ($fields as $field) {
    if ($node->hasField($field) && isset($node->get($field)[0])) {
        $field_value = $node->get($field)[0]->getValue(); // Array with format and value (i.e. text)
        $text = $field_value['value'];

        if (stristr($text, 'data-entity-type="media"') !== FALSE) {
          $dom = Html::load($text);
          $xpath = new \DOMXPath($dom);

          // Fill array with image UUID
          foreach ($xpath->query('//*[@data-entity-type="media" and @data-entity-uuid]') as $image) {
            $uuids[] = $image->getAttribute('data-entity-uuid');
          }
        }
      }
  }

  // Load media items. Fill Name with Alt text and Image_category with node type.
  if (count($uuids) !== 0) {

    $uuids = array_unique($uuids); // De-dup the array.

    // Get the taxonomy term id for the node type to fill the image_category field.
    $image_cat = imagecategory::getImageCatTid($node);

    foreach ($uuids as $key => $uuid) {
      $media = \Drupal::entityTypeManager()->getStorage('media')->loadByProperties(['uuid' => $uuid]);

      if ($media) {
        $media = reset($media);
        $alt = $media->get('thumbnail')[0]->get('alt')->getString();
        $bundle = $media->get('bundle')->getString();

        if ($alt) {
          $media->set('name',$alt)->save();
        }
        if (!in_array($bundle, ['public_file','restricted_file','remote_video','video']) and $image_cat) {
          $media->set('field_image_category',$image_cat)->save();
        }
      }
    }
  }

  // Fill Name field with Alt text for paragraph components.
  if (isset($node->field_components)) {

    $entities = $node->get('field_components')->referencedEntities();
    foreach ($entities as $key => $entity) {
      $id = $entity->id();
      $p = \Drupal\paragraphs\Entity\Paragraph::load($id);
      $ptype = $p->bundle();

      // Get media ID if Paragraph type has image field.
      if($ptype == 'card') {
        $mid = $p->field_image->target_id;
      } elseif ($ptype == 'text_and_4_3_image' | $ptype == 'text_and_16_9_image') {
        $mid = $p->field_aligned_image->target_id;
      } else {
        $mid = NULL;
      }

      // Set image name equal to alt text.
      if ($mid) {
        $media = Media::load($mid);
        $alt = $media->get('thumbnail')[0]->get('alt')->getString();
        if ($alt) {
          $media->set('name',$alt)
          ->save();
        }
      }
    }
  }
}
