<?php

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\club_test\CleanPermissions;

/*
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Component\Datetime\DateTimePlus;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;

use Drupal\club_leader\AddYear;
use Drupal\club_ride\UpdateCoauthors;
use Drupal\club_schedule\LoadSchedule;

use Drupal\club_test\AddEventDates;
use Drupal\club_test\AddRecurDates;
use Drupal\club_test\AssignBasedOn;
use Drupal\club_test\CleanPermissions;
use Drupal\club_test\FixRides;
use Drupal\club_test\FixRoutes;
use Drupal\club_test\FixWed;
use Drupal\club_test\ListMaxID;
use Drupal\club_test\ResaveNodes;
*/

/*
 * Implement hook_help.
 * Test code is written to help page
 */
function club_test_help($route_name, RouteMatchInterface $route_match) {

  if ($route_name == 'help.page.club_test') {

    CleanPermissions::dropPermissions();

  /*
  // Add Year to Club Leader records.
    AddYear::createYear();

  // Test code to add coauthors to ride pages.  
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');
		$nids = [1242,2885];

    foreach($nids as $nid) {
      $node = $node_storage->load($nid);

      // Use form values not node values?
      $coauthors = $node->get('co_authors')->getValue();
      $leaders = $node->get('field_ride_leader')->getValue();

      $numCoauthors = count($coauthors);
      $numLeaders = count($leaders);

      if ($numCoauthors == 0 and $numLeaders > 0) {
        // Fill coauthors the first time the ride is saved.
        updateCoauthors::addCoauthors($node, $leaders);

      } else {
         // If form-leaders ! = original-leaders
          if ($numCoauthors > 0) {
            updateCoauthors::deleteCoauthors($nid);
          }
          updateCoauthors::addCoauthors($node, $leaders);
        } 
    }
*/

    //FixRoutes::resaveRides('recurring_ride');
    //AddEventDates::addEventDates();
    //AddRecurDates::addRecurDates();
    //LoadSchedule::loadSchedule();
    /**
     * For new Master List: 
     * (1) Run FixRides for rides and recurring_rides to set Master = 1 (default value).
     * (2) Run AssignBasedOn to set Master = 0 and BasedOn = Master_NodeID 
     * (3) Run FixWed to convert Wenesday Morning Rotating Rides from recurring_ride to ride
     *     (this assigns new NodeID so run this last)
     * 
     * FixRides::resaveRides('ride');
     * FixRides::resaveRides('recurring_ride');
     * AssignBasedOn::addBasedOn();
     * FixWed::convertWed();
     * AddRecurDates::dropRecurDates(); // Delete all recurring_dates before re-generating them.
     * ResaveNodes::loadNodes('ride');
     * ListMaxID::getMax();
     */
  }
}
