<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_alter().
 */
function club_announcement_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  if ($form_id == 'node_announcement_form') {
    // Fill datetime field in Scheduler on initial page creation when scheduling is REQUIRED
    $date = strtotime(date('Y-m-d 01:00:00'));
    $form['publish_on']['widget'][0]['value']['#default_value'] = DrupalDateTime::createFromTimestamp($date);
    $form['unpublish_on']['widget'][0]['value']['#default_value'] = DrupalDateTime::createFromTimestamp($date);
  }
}
