<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\comment\CommentInterface;
use Drupal\club\GetTermId;
use Drupal\club\CheckRoles;

/**
 * Implements hook_theme().
 * CSS is "attached" in Twig.
 */
function club_forum_theme() {
  return [
    // Provide a default template for Forums.
    'node__forum__full' => [
      'base hook' => 'node',
    ],
    'form__comment_comment_forum_form' => [
      'base hook' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function club_forum_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  // FORUM POST.
  if ($form_id == 'node_forum_form') {

    // Get termId for Unofficial rides forum.
    $rideTerm = GetTermId::getTermId('forums', 'Unofficial Rides and Other Activities');

    // Show ride date on Unofficial Ad-Hoc Rides form.
    $form['field_ride_date']['#states'] = [
      'visible' => [
        ':input[name^="taxonomy_forums"]' =>  ['value' => $rideTerm],
      ],
    ];

    // Disable access to field_anonymous for club leaders on forum posts.
    $isLeader = CheckRoles::isLeader();

    if ($isLeader == 1) {
      $form['field_anonymous']['#access'] = false;
    } else {
      // Hide field_anonymous for everyone else if forum = Unofficial rides.
      $form['field_anonymous']['#states'] = [
        'invisible' => [
          ':input[name^="taxonomy_forums"]' =>  ['value' => $rideTerm],
        ],
      ];
    }
  }

  // FORUM COMMENT;
  elseif ($form_id == 'comment_comment_forum_form') {

    // Taxonomy term is stored in the NODE obect.
    // Get comment from form object, then get commented entity (node) from the comment.
    // Finally, get taxonomy term from node object.
    $form_object= $form_state->getFormObject();
    $comment = $form_object->getEntity();
    $node = $comment->getCommentedEntity();
    $nodeTerm = $node->get('taxonomy_forums')->target_id;

    // Get termId for Unofficial rides forum.
    $rideTerm = GetTermId::getTermId('forums', 'Unofficial Ad-Hoc Rides');

    // Disable access to field_anonymous for club leaders on forum comments.
    $isLeader = CheckRoles::isLeader();

    if ($isLeader == 1) {
      $form['field_anonymous']['#access'] = false;
    }   
    // Hide field_anonymous for nonleaders when commenting on Unofficial rides.
    elseif ($nodeTerm == $rideTerm) {
      $form['field_anonymous']['#access'] = false;
    } 
  }
}
  
/**
 * Implements hook_node_presave().
 *
 */
function club_forum_node_presave(EntityInterface $node) {
  $bundle = $node->bundle();

  // If node is a forum topic and posting anonymously.
  if ($bundle == 'forum' and $node->field_anonymous->value == 1) {
    // Anonymize author.
    $node->setOwnerId(0);
  }
}

/**
 * Implements hook_comment_presave().
 *
 */
function club_forum_comment_presave(CommentInterface $comment) {
  $bundle = $comment->bundle();

  // If comments are in a forum and posting anonymously.
  if ($bundle == 'comment_forum' and $comment->field_anonymous->value == 1) {
    // Anonymize author.
    $comment->setOwnerId(0);
  }
}
