<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_node_presave().
 *
 */
function club_location_node_presave(EntityInterface $node) {

  if($node->bundle() == 'location') {

    // Display message if GoogleMaps API is empty.
    $googleAPI = \Drupal::config('geocoder.geocoder_provider.googlemaps')->get('configuration.apiKey');
    if (!$googleAPI) {
      $link = \Drupal\Core\Url::fromRoute('entity.geocoder_provider.collection')->toString();
      $content = 'Please configure a <a href="@link">geocoder provider</a> to geocode addresses and display them on a map.
      (The Google Maps link is valid even if not geocoded.)';

      \Drupal::messenger()->addWarning(t($content, [ '@link' => $link ]));
    }

    // Fill GoogleMap field.
    if(isset($node->field_coordinates)) {
      $address = $node->field_address->getValue();

      $street = $address[0]['address_line1'];
      $city   = $address[0]['locality'];
      $state  = $address[0]['administrative_area'];
      $zip    = $address[0]['postal_code'];

      $uri = "https://www.google.com/maps/place/" . $street . "+" . $city . "+" . $state . "+" . $zip;

      $coord = $node->field_coordinates->getValue();

      if ($coord) {
        $uri = $uri . "/@" . $coord[0]['lat'] . "," . $coord[0]['lon'];
      }

      $node->field_google_map = [
          "uri" => $uri,
          "title" => "Google map",
          "options" => ["target" => "_blank"]
        ];
    }
  }
}
