_core:
  default_config_hash: azOklU3-VWHb425Xf5EbPrnutd-lfpxriolAjXU-eDs
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
logo:
  use_default: 0
  path: 'public://header.svg'
favicon:
  use_default: 0
  path: 'public://NSC favicon.jpg'
  mimetype: image/jpeg
d8w3css_font_awesome_4: 1
d8w3css_google_font: 1
website_width: w3-width-100-percent
full_opacity_onscroll: 0
top_region: 1
main_region: 1
bottom_region: 1
footer_region: 1
equal_width: 1
current_theme: w3-theme-blue-grey
color_page_wrapper: ''
color_header: w3-white
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: w3-white
color_top_container: ''
color_top_first: ''
color_top_second: ''
color_top_third: ''
color_page_title: ''
color_main: w3-white
color_breadcrumb: ''
color_sidebar_first: w3-white
color_content: w3-white
color_sidebar_second: w3-white
color_bottom_container: ''
color_bottom_first: 'w3-white w3-round-small w3-text-grey'
color_bottom_second: 'w3-white w3-round-small w3-text-grey'
color_bottom_third: 'w3-white w3-round-small w3-text-grey'
color_bottom_forth: 'w3-white w3-round-small w3-text-grey'
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: ''
color_copyright: ''
show_social_icon: 1
facebook_url: 'https://www.facebook.com/groups/nscyclists/members/'
twitter_url: ''
pinterest_url: ''
google_plus_url: ''
linkedin_url: ''
instagram_url: ''
youtube_url: ''
drupal_url: ''
rss_url: ''
copyright_text: ''
show_credit_link: 0
rwgps_url: /ride-gps-club-account
strava_url: ''
topnav: 1
alert_bgcolor: null
cancel_bgcolor: w3-vivid-orange
layout_user_login_custom: 0
sitename_animation: none
pagetitle_animation: none
border_animation: 0
d8w3css_google_font_local: 0
d8w3css_site_gf: none
d8w3css_site_gfh: none
d8w3css_site_gfs: none
solid_footer: 1
breadcrumb_page_title: 0
d8w3css_font_awesome: '0'
image_captions: 0
mastodon_url: ''
social_media_size: null
