tac_lite_categories:
  page_access: page_access
tac_lite_schemes: '1'
menu_rebuild_needed: true
tac_lite_config_scheme_1:
  name: 'View access'
  perms:
    grant_view: grant_view
  unpublished: 0
  term_visibility: 0
tac_lite_grants_scheme_1:
  anonymous:
    page_access: {  }
  authenticated:
    page_access: {  }
  administrator:
    page_access:
      19: '19'
      31: '31'
      20: '20'
  member:
    page_access:
      19: '19'
  editor:
    page_access:
      31: '31'
      20: '20'
  ride_leader:
    page_access:
      31: '31'
  rides_coordinator:
    page_access:
      31: '31'
      20: '20'
  civicrm:
    page_access:
      31: '31'
      20: '20'
  site_admin:
    page_access:
      31: '31'
      20: '20'
  board:
    page_access:
      31: '31'
      20: '20'
