<?php

use Drupal\club\ImageCategory;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function club_media_views_pre_render(ViewExecutable $view) {

  // If view is banner and display is grid.
  if ($view->id() == "banner" &&
     ($view->current_display == 'gallery_home' || $view->current_display == 'gallery_other')) {

      // Condition on total_rows>0 because block layout includes both gallery & banner views
      if ($view->total_rows > 0) {
        // Dynamically set column options equal to #images (total_rows).
        $view->getStyle()->options['columns'] = $view->total_rows;

        // Get value of field_gallery_padding
        $padding = $view->result[0]->_entity->field_padding->getValue()[0]['value'];

        // Dynamically apply padding css
        if ($padding == 0) {
          $view->getStyle()->options['col_class_custom'] = 'gallery-pad';
        } else {
          $view->getStyle()->options['col_class_custom'] = 'gallery-nopad';
        }
      }
    }
  }

/**
 * Implements hook_node_presave().
 *
 */
function club_media_node_presave(EntityInterface $node) {

  if ($node->bundle() == 'banner') {

    // Load image entities (Limit = unlimited).
    $entities = $node->get('banner_image')->referencedEntities();

    foreach ($entities as $key => $entity) {
      $mid = $entity->id();  // Media ID.

      $media = Media::load($mid);
      $alt = $media->get('thumbnail')[0]->get('alt')->getString();

      if ($alt) {
        $media->set('name',$alt)->save();
      }
    }
  }
}
/**
 * Implements hook_local_actions_alter().
 */
function club_media_menu_local_actions_alter(&$local_actions) {
  // Check if the 'media.add' action exists and unset it.
  // Media should be added only via content pages.
  if (isset($local_actions['media.add'])) {
    unset($local_actions['media.add']);
  }
}
