<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\Role;
use Drupal\user\Entity\User;
use Drupal\club\GetTermId;

/**
 * Implements hook_form_ID_alter().
 */
function club_leader_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  //\Drupal::messenger()->addStatus('Form ID: ' . $form_id);

  // Add/edit club leader form. 
  if ($form_id == 'club_contacts_form') {

    // Hide 'name' field on Add form (id is missing when adding content).
    if (!$form_state->getformObject()->getEntity()->id()) {
      $form['name']['#access'] = FALSE;
    }

    // Hide 'board term' unless position = 'Board of Directors' on Add and Edit forms.
    $board_id = GetTermId::getTermId('positions', 'Board of Directors');

    if ($board_id) {
      // Hide 'board term' unless position = 'Board of Directors' is selected.
      $form['board_term']['#states'] = [
        'visible' => [
          ':input[name="position"]' => ['value' => $board_id],
        ],
      ];
    } else {
      //  Hide 'board term' if position = 'Board of Directors' does not exist.
      $form['board_term']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_ID_alter().
 */
function club_leader_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $formState, $form_id) {

  // Alter taxonomy terms listing to display additional fields.
  // Get vocabulary name from path (cannot get it from formState because its protected)
  $path = \Drupal::request()->getpathInfo();
  $arg = explode('/', $path);

  
  // Club positions
  if ($arg[5] == "positions") {
    $form['terms']['#header'] = array_merge(array_slice($form['terms']['#header'], 0, 1, TRUE),
      [t('Category')],
      [t('Drupal role')],
      [t('Disabled')],
      array_slice($form['terms']['#header'], 1, NULL, TRUE)
    );

    foreach ($form['terms'] as &$term) {
      if (is_array($term) && !empty($term['#term'])) {

        $disabled = ($term['#term']->get('field_disabled')->value == 1 ) ? "yes" : "-";

        if (null != $term['#term']->get('field_website_role')->entity) {
          $web_role = $term['#term']->get('field_website_role')->entity->label(); 
        } 
        else {
          $web_role = NULL;
        }

        $category['Category'] = [
          '#markup' => $term['#term']->get('field_position_category')->value,
          '#type' => 'item',
        ];
        $role['Drupal role'] = [
          '#markup' => $web_role, 
          '#type' => 'item',
        ];
        $dropped['Disabled'] = [
          '#markup' => $disabled,
          '#type' => 'item',
        ];
       
        $term = array_merge(
          array_slice($term, 0, 1, TRUE),
          $category, $role, $dropped,
          array_slice($term, 1, NULL, TRUE),
        );

      }
    }
  }
}

/**
 * Implements hook_entity_presave().
 *
 *  TODO: cron job to remove user roles if end date < today
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   club_contacts.
 *
 * @see hook_entity_presave()
 */
function club_leader_club_contacts_presave(EntityInterface $club_contacts) {
  $end = $club_contacts->field_end_date->value;
  $position = $club_contacts->position->target_id;

  $isCurrentPos = (empty($end) or $end > date('Y-m-d'));
  
  // If contact is a Drupal user
  if ( !empty($club_contacts->contact->entity) ) {

    // Fill 'name' so we don't lose name if user account is cancelled.
    if ($club_contacts->name->value == NULL) {
      $club_contacts->name = $club_contacts->contact->entity->label();
    }

    // Fill Year (integer) because using year of start date creates separate groups for different
    // start date in same year.
    $date_value = $club_contacts->field_start_date->value;
    $date_time = new DrupalDateTime($date_value, new \DateTimeZone('UTC'));
    $club_contacts->year = $date_time->format('Y');
    
    // Load position, fill 'role', assign_role
    if (!is_null($position)) {
      $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($position);
      $club_contacts->role = $term->get('field_website_role')->target_id;

      // Assign Drupal user role
      if (null != $club_contacts->role ) {
        $user = User::load($club_contacts->contact->target_id);
        $role = $term->get('field_website_role')->target_id;

        // Add or delete role depending on isCurrentPos
        assign_role($user, $role, $isCurrentPos);
      }
    }
	}
}

/**
 * Function called by club_club_contacts_presave
 * Assign Drupal user role if isCurrent; remove role if end date is entered
 */
function assign_role(EntityInterface $update_user, $role, $isCurrent) {
  $admin_role = Role::load($role)->id();

  if ($isCurrent & !$update_user->hasRole($admin_role)) {
    $update_user->addRole($admin_role);
    $update_user->save();
  } else if ($update_user->hasRole($admin_role) & !$isCurrent) {
    $update_user->removeRole($admin_role);
    $update_user->save();
  }
}

/**
 * Implements hook_entity_update().
 *
 */
function club_leader_club_contacts_update(EntityInterface $club_contacts) {
  $orig = $club_contacts->original;

  // If position is changed.
  if ( $club_contacts->position->target_id != $orig->position->target_id )  {

    $user = User::load($orig->contact->target_id);

    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($orig->position->target_id);
    $role = $term->field_website_role->target_id;

    // Remove Drupal role associated with original position when club position is changed.
    if (!empty($role)) {

      if ($user->hasRole($role)) {
        $user->removeRole($role);
        $user->save();
      }
    }
  }

}

/**
 * Implements hook_entity_delete().
 */
function club_leader_club_contacts_delete(EntityInterface $club_contacts) {

  // When contact record is deleted, remove Drupal role from user if:
  //  contact is Drupal user and position field is filled.
  if ( !empty($club_contacts->contact->entity) and !is_null($club_contacts->position->target_id) ) {
    $user = User::load($club_contacts->contact->target_id);

    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($club_contacts->position->target_id);
    $role = $term->field_website_role->target_id;

    // Remove Drupal role associated with the position when club leader is deleted.
    if (!empty($role)) {

      if ($user->hasRole($role)) {
        $user->removeRole($role);
        $user->save();
      }
    }
  }
  return;
}
