<?php

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\UserInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_local_tasks_alter().
 */
function club_user_local_tasks_alter(&$local_tasks) {
  // Hide tabs above Login form
  unset($local_tasks["user.pass"]);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function club_user_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface $cacheability) {
  // Change tab title on the "My Accounts" page.
  // And display in admin theme if viewer is not current user (this gets rid of sidebar block w/current user info)

  $routes = ['entity.user.canonical','view.club_rides.my_rides',
             'view.user_account.my_events','view.user_account.my_payments'];

  if (in_array($route_name, $routes)) {
    $data['tabs'][0]['entity.user.canonical']['#link']['title'] = 'Member Info';
  }

  // Remove tabs from the user page.
  unset($data['tabs'][0]['entity.user']);
  unset($data['tabs'][0]['entity.user.edit_form']);
  unset($data['tabs'][0]['shortcut.set_switch']);
  unset($data['tabs'][0]['role_delegation.edit_form']);
  unset($data['tabs'][0]['entity.webform_submission.user']);
  unset($data['tabs'][0]['devel.entities:user.devel_tab']);
  unset($data['tabs'][0]['views_view:view.scheduler_scheduled_content.user_page']);

  // Remove tabs from the personal contact form page.
  if ($route_name == 'entity.user.contact_form') {
    unset($data['tabs'][0]);
  }

  // Check if current user has current membership. If no, display message.
  // Use Drupal user id to get CiviCRM Contact ID, then use Contact ID query membership.
  // Code assumes Multiple Memberships have been resolved.

  $current_path = \Drupal::service('path.current')->getPath();

  // Execute code when path is in the form /user/xxxx, where xxx = user id

  $path = substr($current_path,0,6);
  $path_id = substr($current_path,6,6);

  // Do not run this check if admin is viewing a user - i.e., user id in URL must match current user
    if ($path === "/user/" and $current_path <> '/user/login') {
    
    $user = User::load(\Drupal::currentUser()->id());
    $user_id = $user->id();

    // Execute if user is viewing their My Account page (do not execute if admin views users)
    if ($path_id === $user_id) {

    $db = \Drupal::database();
    $match = $db->query("SELECT contact_id FROM {civicrm_uf_match} WHERE id = :user_id", [':user_id' => $user_id, ])
    ->fetch();
    $contact_id = json_decode(json_encode($match), true);

    if ($contact_id) {
      $contact_id = reset($contact_id);

      $member = $db->query("SELECT status_id FROM {civicrm_membership} WHERE contact_id = :contact_id", [':contact_id' => $contact_id, ])
      ->fetch();
    
      if ($member) {
        $status_id = json_decode(json_encode($member), true);
        $status_id = reset($status_id);

        if ($status_id > 2) {
          \Drupal::messenger()->addError("Your membership is not current. See MEMBERSHIP INFO at lower left on this page");
        }
      }
    }
  }
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function club_user_menu_local_actions_alter(&$local_actions) {
  // People > List: remove 'Add user' button (users are managed through memberships)
  unset($local_actions["user_admin_create"]);
  // People > Event participants: remove 'Add participant' button
  unset($local_actions["civicrm.civicrm_participant_add"]);
  // People > Contacts: remove 'New contact' button
  unset($local_actions["civicrm.civicrm_contact_add"]);
}

/**
 * Implements hook_form_alter().
 */
function club_user_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
 // \Drupal::messenger()->addStatus('Form ID: ' . $form_id);

 if (!$form_id == 'entity_view_display_layout_builder_form') {
  switch ($form_id) {
    // Password description text (see core/modules/user/src/form/UserLoginForm.php)
    case 'user_login_form':
      $form['pass']['#description'] = t('Forgot your <a href="/user/password"><strong>password?</strong></a>');
      //$form['#submit'][] = 'club_user_login_submit';
    break;

    // Password reset form
    case 'user_pass':
      $form['name']['#title'] = t('Email address');
      $form['mail']['#markup'] = t('Reset instructions will be sent to your email address. Be sure to check your spam or junk folder.<br>If you do not find an email, contact the
         <a href="/contact/membership"><strong>Membership Coordinator</strong></a>.<br>Return to <a href="/user/login"><strong>Log in</strong></a> page.');
    break;

    // Hide name, status, roles on Own account so users edit only "email, password, photo" (name is set in CiviCRM)
    // Language, timezone, contact are hidden by Configuration > People > Account settings > Form display
    case 'user_form':
      $path = \Drupal::request()->getpathInfo();
      $arg = explode('/', $path);
      $currentUser = \Drupal::currentUser()->id();

      if ($arg[1] == 'user' && $arg[2] == $currentUser) {
        $form['account']['name']['#access'] = FALSE;
        $form['account']['status']['#access'] = FALSE;
        $form['account']['roles']['#access'] = FALSE;
      }
    break;

    // Display warnings on My Account webforms when admin views another user (admin's info is loaded)
    case 'webform_submission_edit_contact_info_add_form':
      $user = $form['elements']['civicrm_1_contact_1_fieldset_fieldset']['civicrm_1_contact_1_contact_existing']['#value'];

      if (\Drupal::currentUser()->id() != $user and  getCurrentAdmin() == 1) {
        \Drupal::messenger()->addError('Form contains YOUR information. Return to PEOPLE menu and use link on CONTACTS page to edit information for other users.');
      }
    break;

    case 'webform_submission_renew_membership_add_form':
      $user = $form['elements']['contact_pagebreak']['civicrm_1_contact_1_contact_existing']['#value'];

      if (\Drupal::currentUser()->id() != $user and getCurrentAdmin() == 1) {
        \Drupal::messenger()->addError('Form contains YOUR information. Use CiviCRM to manually renew membership for another user.');
      }
    break;

    case 'contact_message_personal_form':
      $form['actions']['submit']['#submit'][] = 'contact_form_redirect';
      break;  
    }
 }
}

/**
 * Functions called by hook_form_alter().
 */
function getCurrentAdmin() {
  $roles = \Drupal::currentUser()->getRoles();

  $currentAdmin = 0;
  if(in_array('administrator',$roles) | in_array('site_admin',$roles) | in_array('civicrm',$roles)) {
	  $currentAdmin = 1;
  }
  return $currentAdmin;
}

function contact_form_redirect(&$form, &$form_state) {
  //Redirect to home page
  unset($_GET['destination']);
  $form_state->setRedirect('<front>' );
}