<?php

/**
 * @file
 * Allows users to manage customizable lists of shortcut links.
 */

use Drupal\user\Entity\Role;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shortcutperrole_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shortcutperrole module.
    case 'help.page.shortcutperrole':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows creating default shortcut per role') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_shortcut_default_set().
 */
function shortcutperrole_shortcut_default_set($account) {
  // Determine the highest rid of user & assign the shortcut set.
  $all_roles = Role::loadMultiple();
  $user_roles = array_flip($account->getRoles());
  $sorted_roles = array_intersect_key($all_roles, $user_roles);
  if ($sorted_roles) {
    $role = end($sorted_roles);
    $config = \Drupal::config('shortcutperrole.settings');
    $set = $config->get('role.' . $role->id());
  }
  $ss = $set ?: 'default';
  return $ss;
}

/**
 * Implements hook_ENTITY_TYPE_delete() for user_role entities.
 */
function shortcutperrole_user_role_delete($role) {
  $config = 'shortcutperrole.settings.role.' . $role->id();
  \Drupal::service('config.factory')->getEditable($config)->delete();
}
