<?php

use Drupal\club_ride\UpdateRecurDates;
use Drupal\Core\Entity\EntityInterface;

require_once __DIR__ . '/includes/club_ride.coauthors.inc';
require_once __DIR__ . '/includes/club_ride.form_alter.inc';
require_once __DIR__ . '/includes/club_ride.presave.inc';

/**
 * Implements hook_ENTITY_TYPE_insert() for node.
 * This fires AFTER THE FIRST TIME an entity is saved to the database.
 */
function club_ride_node_insert(EntityInterface $node) {
  if ($node->bundle() == 'recurring_ride') {
    UpdateRecurDates::addDates($node);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node.
 */
function club_ride_node_delete(EntityInterface $node) {

  // When recurring ride is deleted, delete recurring dates.
  if ($node->bundle() == 'recurring_ride') {
  
    // Select recurring_dates with field_recurid = recurring_ride node ID. 
    $ids = \Drupal::entityQuery('node')
      ->condition('field_recurid', $node->id())
      ->accessCheck(FALSE)
      ->execute();

    $storageHandler = \Drupal::entityTypeManager()->getStorage('node');
    $entities = $storageHandler->loadMultiple($ids);

    foreach ($entities as $recur_date) {
      $recur_date->delete();
    }
  }
}

